 import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
// Import your Provider component - adjust the import path as needed
 import Provider from "./Provider"; // Replace with actual path

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}